version: 2
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home-sidebar
  timestamp: 1460316668
layout:
  /header/:
    -
      - logo-2428
  /navigation/:
    -
      - menu-6127
  /showcase/: {  }
  /feature/: {  }
  /container-main/:
    -
      -
        'main 80':
          -
            - system-messages-3209
          -
            - 'logo-7717 20'
            - 'system-content-4953 80'
      -
        'sidebar 20': {  }
  /subfeature/: {  }
  /footer/:
    -
      - position-footer
    -
      - 'copyright-4178 33.3'
      - 'social-8370 33.3'
      - 'branding-8356 33.3'
  offcanvas:
    -
      - mobile-menu-5508
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  showcase:
    type: section
    attributes:
      boxed: ''
  feature:
    type: section
    attributes:
      boxed: ''
  sidebar:
    type: section
  container-main:
    attributes:
      boxed: ''
  subfeature:
    type: section
    attributes:
      class: flush
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  logo-2428:
    title: 'Logo / Image'
    attributes:
      url: ''
      image: 'gantry-media://damon-logo.jpg'
      text: 'Damon Jespersen-Selectman'
      class: ''
  menu-6127:
    attributes:
      menu: main
  logo-7717:
    title: 'Logo / Image'
    attributes:
      image: 'gantry-media://damon-photo2.jpg'
      text: 'Damon Jespersen-Selectman'
      class: ''
    block:
      variations: nomarginall
  system-content-4953:
    block:
      variations: align-left
      extra:
        -
          style: 'background-color:#ffffff;'
  position-footer:
    attributes:
      key: footer
  social-8370:
    attributes:
      css:
        class: social-items
      items:
        -
          icon: 'fa fa-twitter'
          text: Twitter
          link: 'http://twitter.com/rockettheme'
          name: Twitter
        -
          icon: 'fa fa-facebook'
          text: Facebook
          link: 'http://facebook.com/rockettheme'
          name: Facebook
        -
          icon: 'fa fa-google'
          text: Google
          link: 'http://plus.google.com/+rockettheme'
          name: Google
        -
          icon: 'fa fa-rss'
          text: RSS
          link: 'http://www.rockettheme.com/product-updates?rss'
          name: RSS
    block:
      variations: center
  branding-8356:
    block:
      variations: align-right
  mobile-menu-5508:
    title: 'Mobile Menu'
