name: _error
timestamp: 1487119580
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1463772952
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-3280: Logo
  spacer:
    spacer-9445: Spacer
    spacer-5026: Spacer
  menu:
    menu-2478: Menu
  content:
    system-content-4474: 'Page Content'
  position:
    position-footer: Footer
  copyright:
    copyright-4713: Copyright
  branding:
    branding-2614: Branding
  mobile-menu:
    mobile-menu-4370: Mobile-menu
inherit: {  }
