name: _body_only
timestamp: 1487119580
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1463772952
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-8300: 'System Messages'
  content:
    system-content-7099: 'Page Content'
inherit: {  }
