version: 2
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1463772952
layout:
  /header/:
    -
      - 'logo-2972 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-1174
  /showcase/: {  }
  /feature/: {  }
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-9861
    -
      - 'system-content-8229 80'
      - 'logo-6969 20'
  /subfeature/:
    -
      - custom-6371
  /footer/:
    -
      - 'copyright-3731 50'
      - 'social-5319 50'
  offcanvas:
    -
      - mobile-menu-6833
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  showcase:
    type: section
    attributes:
      boxed: ''
  feature:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  subfeature:
    type: section
    attributes:
      class: flush
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  logo-2972:
    attributes:
      image: 'gantry-media://damon-logo.jpg'
      text: 'Damon Jespersen-Selectman'
      class: ''
  position-header:
    attributes:
      key: header
  menu-1174:
    attributes:
      menu: main
    block:
      variations: align-right
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  logo-6969:
    title: 'Logo / Image'
    attributes:
      image: 'gantry-media://damon-jespersen.png'
      link: '0'
      text: 'Damon Jespersen, Selectman'
      class: ''
  custom-6371:
    title: 'Custom HTML'
    attributes:
      html: '<h1>Vote Damon Jespersen for Selectman</h1>'
    block:
      variations: center
  copyright-3731:
    attributes:
      owner: 'Damon Jespersen'
  social-5319:
    block:
      variations: align-right
