version: 2
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1463772952
layout:
  /header/:
    -
      - 'logo-5888 30'
      - 'spacer-4917 70'
  /main/:
    -
      - system-messages-1227
    -
      - system-content-1116
  /footer/:
    -
      - position-footer
    -
      - 'copyright-6013 40'
      - 'spacer-9655 30'
      - 'branding-2829 30'
structure:
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
